### ISSUE TITLE
Chrome에서 반응형 웹페이지 화이트 스페이스 수정 방법

### ISSUE THREAD

**Issue by ineggapps** [ineggapps/html5-css3-benchmarking#1]
# Chrome에서 반응형 웹페이지 화이트 스페이스 수정 방법

## 1. 문제의 발단
Chrome에서 반응형 웹페이지를 만들다가 가로폭을 줄이면서 세로줄에 흰 공백이 생기는 것을 발견하였다. 
![반응형웹 이미지 화이트스페이스](https://i.imgur.com/0QVGphT.png)
이걸 어쩌면 좋지 싶었는데 ㅠㅠ

### 2.1. div 레이아웃의 wrapper의 최소 폭 지정
깨지기 전의 최적화된 최소폭을 지정하여 다음과 같이 미디어쿼리로 가로폭을 고정해 준다.
```css
/*레이아웃 깨짐 방지*/
@media (max-width: 400px) {
  #login_wrap {
    min-width: 400px;
  }
}
```
### 2.2 화이스스페이스 없애기
다음의 CSS 항목을 추가해 준다. (이건 미디어쿼리 아님!!)
```css
html,
body {
  /* white space bug fix in chrome */
  margin: 0px;
  padding: 0px;
  overflow-x: hidden;
}
```
참고로 firefox에서는 이러한 화이트스페이스 버그가 발견되지 않았음.

문제해결은 다음의 페이지에서 참조하였음.
구글 검색 키워드: chrome responsive widthwhite-space bug
[참조: stackoverflow](https://stackoverflow.com/questions/39070028/mysterious-white-space-at-bottom-of-web-page-in-mobile-chrome) 

### 2.3. 문제가 해결된 뒤.

다행히 문제가 해결되었다.
카카오스토리 로그인 페이지를 따라했는데 화이트스페이스가 떠서 당황하였음.
이제 가로폭을 줄여도 스크롤이 생길 뿐 세로에 화이트스페이스가 발생하지 않는다.
![반응형웹 이미지 화이트스페이스 수정](https://i.imgur.com/JNoYwrE.png)
